
version: 2
updates:
  # Enable version updates for pyproject.toml, poetry.lock, and requirements.txt
  - package-ecosystem: "pip"
    # Look for files in the `root` directory
    directory: "/"
    # Check the pip registry for updates every week
    schedule:
      interval: "weekly"

  # Enable version updates for environment.yml
  - package-ecosystem: "conda"
    directory: "/"
    schedule:
      interval: "weekly"
