name: spinneret
channels:
  - conda-forge
  - defaults
dependencies:
  - geopandas
  - pytest-mock
  - daiquiri
  - sphinx-autoapi
  - pylint
  - matplotlib
  - lxml
  - pytest-cov
  - pandas
  - myst-parser
  - python-semantic-release
  - sphinx
  - pytest
  - python=3.11.11
  - black
  - rdflib
prefix: /opt/miniconda3/envs/spinneret
